### ISSUE TITLE
Array element mismatch

### ISSUE THREAD

**Issue by arichiardi** [aengelberg/loco#8]
Hello Alex!

I tried to define:

    (def send
      (for [i (range 4)]
        ($in [:send i] 0 9)))

    (concat send
          more
          money
          letter-ties
          carries [($distinct send
                     ...

But I get:

    1. Unhandled java.lang.IllegalArgumentException array element type mismatch
                    Array.java:   -2  java.lang.reflect.Array/set
                       RT.java: 1719  clojure.lang.RT/seqToTypedArray
                      core.clj: 3319  clojure.core/into-array
               constraints.clj:  541  loco.constraints/eval14873/fn
                  MultiFn.java:  233  clojure.lang.MultiFn/invoke
                      core.clj:   99  loco.core/eval-constraint-expr
                      core.clj:  135  loco.core/problem->solver
                      core.clj:  184  loco.core/solution
                   RestFn.java:  410  clojure.lang.RestFn/invoke
                cp_samples.clj:   72  assignments.cp-samples/sol
                          REPL:    1  assignments.cp-samples/eval16935

What am I doing wrong?

Note: it works with:

    ($distinct [[:send 3] [:send 2] [:send 1] [:send 0]])

**Comment by Engelberg** [comment]
$distinct wants a bunch of variables so ($distinct [[:send 3] [:send 2] [:send 1] [:send 0]]) is correct.

You're passing it send, which evaluates to a bunch of constraints [($in [:send 0] 0 9) ($in [:send 1] 0 9) ($in [:send 2] 0 9) ($in [:send 3] 0 9)].  Does that make sense?

I'd probably write it like:

```clojure
(def send (for [i (range 4)] [:send i]))
(def send-constraints (for [v send] ($in v 0 9)))
```
Then ($distinct send) will work as expected.

**Comment by arichiardi** [comment]
Right! Sorry about that :)
